allow header and set header in client
ipfs/go-ipfs-cmds pull request #222
Opened 2021-12-16 01:45 UTC by hunjixin

2021-12-16 01:51 UTC, hunjixin commented
@Stebalien

2021-12-27 03:29 UTC, hunjixin commented
anyone can review this pr?

2021-12-27 04:30 UTC, Stebalien requested changes
The change seems reasonable, but please add a test in http/client_test.go (see the first test as a good example).

2021-12-27 04:30 UTC, Stebalien commented on http/config.go
> +	cfg.corsOpts.AllowedHeaders = append(cfg.corsOpts.AllowedHeaders, headers...)
This should either be called `AddAllowedHeaders` or it should set (not append) the allowed headers.

2021-12-27 04:30 UTC, Stebalien commented on http/client.go
> +// ClientWithUserAgent specifies the HTTP user agent for the client.
Incorrect docs.

2022-01-07 17:01 UTC, BigLep commented
@hunjixin: are you able to add the test so we can get this merged?

2022-01-10 06:08 UTC, hunjixin commented
@BigLep  have tested

2022-01-14 17:14 UTC, BigLep commented
Thanks.  We're blocked on finding maintainer review time.  It's in the queue though.

2022-02-12 01:21 UTC, Stebalien approved these changes

2022-02-12 01:21 UTC, Stebalien commented on http/client.go
> +func ClientWithHeaders(key, value string) ClientOpt {
nit

```suggestion
// ClientWithHeader adds an HTTP header to the client.
func ClientWithHeader(key, value string) ClientOpt {
```

2022-02-12 01:21 UTC, Stebalien commented on http/client_test.go
> +		c := NewClient(tc.host, ClientWithHeaders(tc.header, tc.value)).(*client)
```suggestion
		c := NewClient(tc.host, ClientWithHeader(tc.header, tc.value)).(*client)
```

2022-02-12 01:27 UTC, merged

2022-02-12 01:28 UTC, Stebalien commented
Merged in https://github.com/ipfs/go-ipfs-cmds/pull/226 (addressing my review). Thanks!